services:
#    worker_user.example:
#        class: Worker\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    worker_user_registration:
        class: Worker\UserBundle\Form\Type\RegistrationFormType
        tags:
            - {name: form.type, alias: worker_user_registration} 
    # worker_user.registration.form.type:
    #     class: Worker\UserBundle\Form\Type\RegistrationFormType
    #     arguments: [%fos_user.model.user.class%, '@service_container']
    #     tags:
    #         - { name: form.type, alias: worker_user_registration }
    #  